# Generated by Django 5.1.5 on 2025-02-04 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_register_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='bio',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='gender',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='is_listener',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='is_teacher',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='proof_document',
            field=models.FileField(null=True, upload_to='proofs/'),
        ),
        migrations.AddField(
            model_name='register',
            name='skills',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
