# Generated by Django 5.1.5 on 2025-02-05 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_register_bio_register_gender_register_is_listener_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='interests',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
