# Generated by Django 5.1.5 on 2025-02-11 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_register_interests'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='full_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
