# Generated by Django 5.1.5 on 2025-02-12 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0006_register_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='is_listener',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='register',
            name='is_teacher',
            field=models.BooleanField(default=False),
        ),
    ]
