# Generated by Django 5.1.5 on 2025-02-12 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0007_alter_register_is_listener_alter_register_is_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
    ]
