# Generated by Django 5.1.5 on 2025-02-12 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0008_register_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='proof_document',
            field=models.FileField(blank=True, null=True, upload_to='proof_videos/'),
        ),
    ]
