# Generated by Django 5.1.5 on 2025-02-12 13:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0010_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='following', to=settings.AUTH_USER_MODEL),
        ),
    ]
