# Generated by Django 5.1.5 on 2025-03-03 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0016_skill_additional_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='payment_type',
            field=models.CharField(choices=[('free', 'Free'), ('paid', 'Paid')], default='free', max_length=10),
        ),
        migrations.AddField(
            model_name='skill',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
