# Generated by Django 5.1.5 on 2025-03-03 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0017_skill_payment_type_skill_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='payment_type',
            field=models.CharField(default='free', max_length=10),
        ),
    ]
