from django.urls import path
from . import views
urlpatterns =[
    path('',views.index),
    path('reg',views.reg),
    path('user_login',views.user_login,name="user_login"),
    path('home',views.home,name="home"),
    path('user_logout',views.user_logout,name="user_logout"),
    path('about',views.about),
    path('classes',views.classes),
    path('contact',views.contact),
    path('facility',views.facility),
    path('view_user',views.view_user,name="view_user"),
    path('profile',views.profile, name="profile"),
    path('edit_profile',views.edit_profile,name="edit_profile"),
    path('forgot_password',views.forgot_password),
    path('reset_password',views.reset_password,name="reset_password"),
    path('delete_user/<int:id>/',views.delete_user,name="delete_user"),
    path('profile_page',views.profile_page,name="profile_page"),
    path('view_profile',views.view_profile,name="view_profile"),
    path('view_profiles',views.view_profiles,name="view_profiles"),
    path('approve_teachers/<int:id>/',views.approve_teachers,name="approve_teachers"),
    path('reject_teachers/<int:id>/',views.reject_teachers,name="reject_teachers"),
    path('follow/<int:id>/',views.follow,name='follow'),
    path('followeprofile_view/<int:id>/',views.followeprofile_view,name="followeprofile_view"),
    path('message_user/<int:id>/', views.message_user, name='message_user'),
    path('toggle_follow/<int:id>/', views.toggle_follow, name='toggle_follow'),
    path("delete_message/<int:message_id>/", views.delete_message, name="delete_message"), 
    path('chat_list/<int:user_id>/',views.chat_list,name="chat_list"),
    path('chat_list',views.chat_list,name="chat_list") ,
    path('skill_list',views.skill_list,name="skill_list") ,
    path('post_skill',views.post_skill,name="post_skill") ,
    path('view_skill',views.view_skill,name="view_skill") ,
    # path('view_skill/<int:id>/',views.view_skill,name="view_skill") ,
    path('edit_skill/<int:id>/', views.edit_skill, name="edit_skill"), 

]