from django.urls import path
from . import views
urlpatterns =[
    path('',views.index),
    path('reg',views.reg),
    path('user_login',views.user_login,name="user_login"),
    path('home',views.home,name="home"),
    path('user_logout',views.user_logout,name="user_logout"),
    path('about',views.about),
    path('classes',views.classes),
    path('contact',views.contact),
    path('facility',views.facility),
    path('view_user',views.view_user,name="view_user"),
    path('profile',views.profile, name="profile"),
    path('edit_profile',views.edit_profile,name="edit_profile"),
    path('forgot_password',views.forgot_password),
    path('reset_password',views.reset_password,name="reset_password"),
    path('delete_user/<int:id>/',views.delete_user,name="delete_user"),
    path('profile_page',views.profile_page,name="profile_page"),
    path('view_profile',views.view_profile,name="view_profile"),
    path('view_profiles',views.view_profiles,name="view_profiles"),
    path('approve_teachers/<int:id>/',views.approve_teachers,name="approve_teachers"),
    path('reject_teachers/<int:id>/',views.reject_teachers,name="reject_teachers"),
    path('follow/<int:id>/',views.follow,name='follow'),
    path('followeprofile_view/<int:id>/',views.followeprofile_view,name="followeprofile_view"),
    path('message_user/<int:id>/', views.message_user, name='message_user'),
    path('toggle_follow/<int:id>/', views.toggle_follow, name='toggle_follow'),
    path("delete_message/<int:message_id>/", views.delete_message, name="delete_message"), 
    path('chat_list/<int:user_id>/',views.chat_list,name="chat_list"),
    path('chat_list',views.chat_list,name="chat_list") ,
    path('post_skill',views.post_skill,name="post_skill") ,
    path('load_subcategories', views.load_subcategories, name='ajax_load_subcategories'),
    path('load_additional_categories',views.load_additional_categories, name='ajax_load_additional_categories'),
    path('view_skill',views.view_skill,name="view_skill") ,
    # path('view_skill/<int:id>/',views.view_skill,name="view_skill") ,
    path('edit_skill/<int:id>/', views.edit_skill, name="edit_skill"), 
    path('category_list',views.category_list,name="category_list") ,
    path('subcategory_list/<int:category_id>/',views.subcategory_list,name="subcategory_list") ,
    path('additionalcategory_list/<int:subcategory_id>/',views.additionalcategory_list,name="additionalcategory_list") ,
    path('skill_list/<int:additionalcategory_id>/', views.skill_list, name='skill_list'),
    path('delete_category/<int:category_id>/',views.delete_category,name="delete_category") ,
    path('add_category',views.add_category,name="add_category") ,
    path('edit_all_categories', views.edit_all_categories, name='edit_all_categories'),
    path('payment_confirmation/<int:skill_id>/', views.payment_confirmation, name='payment_confirmation'),
    path('make_payment/<int:skill_id>/', views.make_payment, name='make_payment'),
    path('process_payment/<int:skill_id>/', views.process_payment, name='process_payment'),
    path('confirm_credit_card_payment/<int:skill_id>/', views.confirm_credit_card_payment, name='confirm_credit_card_payment'),
    path('payment_success/<str:transaction_id>/<str:amount>/', views.payment_success, name='payment_success'),
    path('view_receipt/<str:transaction_id>/', views.view_receipt, name='view_receipt'),
    path("upi_selection/<int:skill_id>/", views.upi_selection, name="upi_selection"),
    path("upi_payment/<int:skill_id>/<str:upi_option>/", views.upi_payment, name="upi_payment"),  # Allow upi_option
    path("confirm_upi_payment/<int:skill_id>/", views.confirm_upi_payment, name="confirm_upi_payment"),
    path('payment-history/', views.payment_history, name='payment_history'),
    path('view_course_video/<str:transaction_id>/', views.view_course_video, name='view_course_video'),
    path('teacher_earnings', views.teacher_earnings, name='teacher_earnings'),
    path('teacher_payment_selection', views.teacher_payment_selection, name='teacher_payment_selection'),
    path('check-payment-status/<int:skill_id>/', views.check_payment_status, name='check-payment-status'),

   
]